name: myenglish
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  dio: ^5.1.2
  flutter_riverpod: ^2.3.2
  intl: ^0.18.0
  connectivity_plus: ^4.0.0
  loading_indicator: ^3.1.0
  resize: ^1.0.0
  shared_preferences: ^2.0.18
  firebase_core: ^2.13.1
  fluttertoast: ^8.2.1
  firebase_messaging: ^14.6.2
  firebase_auth: ^4.2.2
  otp_text_field: ^1.1.3
  razorpay_flutter: ^1.3.4
  flutter_paypal: ^0.2.0
  url_launcher: ^6.1.7
  file_picker: ^5.2.4
  video_player: ^2.4.10
  video_thumbnail_imageview: ^0.0.5
  video_thumbnail:
    path: ./local_plugins/video_thumbnail-0.5.3
  image_picker: ^0.8.6
  cached_network_image: ^3.3.1
  permission_handler: ^10.2.0
  flutter_cached_pdfview: ^0.4.1
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.0.14
  auto_size_text: ^3.0.0
  
  omni_jitsi_meet:
    path: ./local_plugins/omni_jitsi_meet-1.0.14
  flutter_rating_bar: ^4.0.1
  firebase_crashlytics: ^3.3.1
  crypto: ^3.0.3
  flutter_downloader: ^1.11.7
  fl_downloader: ^2.0.2
   # Changed from a local path to the hosted version
  lottie: ^2.2.0
  chewie: ^1.8.0
  intl_phone_field:
    path: packages/country_code_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli/Muli-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Muli/Muli-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Muli/Muli-Light.ttf
          weight: 300
        - asset: assets/fonts/Muli/Muli-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Muli/Muli.ttf
          weight: 400
        - asset: assets/fonts/Muli/Muli-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Muli/Muli-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Muli/Muli-Semi-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/Muli/Muli-BoldItalic.ttf
          weight: 700
          style: italic